/**
 * Mock Data - Data contoh untuk development dan demo
 * @module store/mockData
 */

// Mock Users
export const MOCK_USERS = [
  {
    id: '1',
    email: 'demo@aksihijau.id',
    password: 'demo123',
    name: 'Ahmad Wijaya',
    phone: '081234567890',
    avatar: null,
    bio: 'Pecinta lingkungan dari Makassar',
    location: 'Makassar, Sulawesi Selatan',
    joinDate: '2024-02-15T00:00:00.000Z',
  },
  {
    id: '2',
    email: 'budi@aksihijau.id',
    password: 'budi123',
    name: 'Budi Santoso',
    phone: '081298765432',
    avatar: null,
    bio: 'Aktivis lingkungan',
    location: 'Makassar',
    joinDate: '2024-03-01T00:00:00.000Z',
  },
  {
    id: '3',
    email: 'sari@aksihijau.id',
    password: 'sari123',
    name: 'Sari Dewi',
    phone: '081355566677',
    avatar: null,
    bio: 'Guru dan pecinta alam',
    location: 'Makassar',
    joinDate: '2024-01-20T00:00:00.000Z',
  },
];

// Mock Trees (untuk user demo)
export const MOCK_MY_TREES = [
  {
    id: 'tree-1',
    userId: '1',
    type: 'mahoni',
    typeName: 'Mahoni',
    location: {
      latitude: -5.1477,
      longitude: 119.4327,
      name: 'Taman Kota Makassar',
    },
    photo: null,
    photos: [],
    notes: 'Ditanam bersama komunitas Aksi Hijau',
    status: 'healthy',
    lastWatered: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tree-2',
    userId: '1',
    type: 'mangga',
    typeName: 'Mangga',
    location: {
      latitude: -5.1355,
      longitude: 119.4228,
      name: 'Jl. Perintis Kemerdekaan',
    },
    photo: null,
    photos: [],
    notes: 'Pohon mangga untuk penghijauan jalan',
    status: 'growing',
    lastWatered: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tree-3',
    userId: '1',
    type: 'trembesi',
    typeName: 'Trembesi',
    location: {
      latitude: -5.1621,
      longitude: 119.4313,
      name: 'Pantai Losari',
    },
    photo: null,
    photos: [],
    notes: 'Pohon rindang untuk teduhan',
    status: 'healthy',
    lastWatered: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tree-4',
    userId: '1',
    type: 'flamboyan',
    typeName: 'Flamboyan',
    location: {
      latitude: -5.1500,
      longitude: 119.4150,
      name: 'Universitas Hasanuddin',
    },
    photo: null,
    photos: [],
    notes: 'Pohon berbunga indah',
    status: 'healthy',
    lastWatered: null,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tree-5',
    userId: '1',
    type: 'jati',
    typeName: 'Jati',
    location: {
      latitude: -5.1400,
      longitude: 119.4200,
      name: 'Taman Macan',
    },
    photo: null,
    photos: [],
    notes: 'Pohon jati untuk konservasi',
    status: 'needs_care',
    lastWatered: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Community Trees
export const MOCK_COMMUNITY_TREES = [
  {
    id: 'c1',
    userId: '2',
    userName: 'Budi Santoso',
    userAvatar: null,
    type: 'mahoni',
    typeName: 'Mahoni',
    location: {
      latitude: -5.1477,
      longitude: 119.4327,
      name: 'Taman Kota Makassar',
    },
    photo: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    userId: '3',
    userName: 'Sari Dewi',
    userAvatar: null,
    type: 'mangga',
    typeName: 'Mangga',
    location: {
      latitude: -5.1355,
      longitude: 119.4228,
      name: 'Jl. Perintis Kemerdekaan',
    },
    photo: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    userId: '2',
    userName: 'Budi Santoso',
    userAvatar: null,
    type: 'trembesi',
    typeName: 'Trembesi',
    location: {
      latitude: -5.1621,
      longitude: 119.4313,
      name: 'Pantai Losari',
    },
    photo: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c4',
    userId: '3',
    userName: 'Sari Dewi',
    userAvatar: null,
    type: 'beringin',
    typeName: 'Beringin',
    location: {
      latitude: -5.1550,
      longitude: 119.4100,
      name: 'Lapangan Karebosi',
    },
    photo: null,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c5',
    userId: '2',
    userName: 'Budi Santoso',
    userAvatar: null,
    type: 'kelapa',
    typeName: 'Kelapa',
    location: {
      latitude: -5.1700,
      longitude: 119.4400,
      name: 'Pantai Akkarena',
    },
    photo: null,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock User Stats (untuk demo user)
export const MOCK_USER_STATS = {
  totalTrees: 5,
  totalPoints: 850,
  co2Absorbed: 125.5, // kg
  streak: 7,
  level: 4,
  levelName: 'Eco Warrior ⚔️',
  todayTarget: 3,
  todayProgress: 1,
};

// Mock Unlocked Achievements
export const MOCK_UNLOCKED_ACHIEVEMENTS = [
  'first_plant',
  'tree_planter',
  'streak_3',
  'streak_7',
];

// Mock Achievement Progress
export const MOCK_ACHIEVEMENT_PROGRESS = {
  first_plant: 5,
  tree_planter: 5,
  tree_guardian: 5,
  forest_maker: 5,
  eco_warrior: 5,
  eco_champion: 850,
  streak_3: 7,
  streak_7: 7,
  streak_30: 7,
  photographer: 3,
  pro_photographer: 3,
  community_hero: 0,
  explorer: 2,
  master_explorer: 2,
  carbon_saver: 125.5,
  climate_hero: 125.5,
};

// Mock RTH (Ruang Terbuka Hijau) Locations in Makassar
export const MOCK_RTH_LOCATIONS = [
  {
    id: 'rth-1',
    name: 'Taman Kota Makassar',
    latitude: -5.1477,
    longitude: 119.4327,
    type: 'taman',
    description: 'Taman kota dengan berbagai jenis pohon',
    treesPlanted: 45,
    area: '2.5 hektar',
  },
  {
    id: 'rth-2',
    name: 'Pantai Losari',
    latitude: -5.1621,
    longitude: 119.4313,
    type: 'pantai',
    description: 'Kawasan pantai dengan penghijauan',
    treesPlanted: 120,
    area: '5 hektar',
  },
  {
    id: 'rth-3',
    name: 'Lapangan Karebosi',
    latitude: -5.1550,
    longitude: 119.4100,
    type: 'lapangan',
    description: 'Lapangan hijau di pusat kota',
    treesPlanted: 80,
    area: '3 hektar',
  },
  {
    id: 'rth-4',
    name: 'Taman Macan',
    latitude: -5.1400,
    longitude: 119.4200,
    type: 'taman',
    description: 'Taman dengan patung macan ikonik',
    treesPlanted: 35,
    area: '1.5 hektar',
  },
  {
    id: 'rth-5',
    name: 'Hutan Kota Antang',
    latitude: -5.1800,
    longitude: 119.4600,
    type: 'hutan_kota',
    description: 'Hutan kota untuk konservasi',
    treesPlanted: 250,
    area: '10 hektar',
  },
  {
    id: 'rth-6',
    name: 'Taman Pattimura',
    latitude: -5.1350,
    longitude: 119.4050,
    type: 'taman',
    description: 'Taman kecil di tengah kota',
    treesPlanted: 25,
    area: '0.8 hektar',
  },
];

// Mock Leaderboard Data
export const MOCK_LEADERBOARD = [
  { rank: 1, userId: '10', name: 'Andi Pratama', points: 5240, trees: 52, avatar: null },
  { rank: 2, userId: '11', name: 'Dewi Lestari', points: 4890, trees: 48, avatar: null },
  { rank: 3, userId: '12', name: 'Rahman Hakim', points: 4520, trees: 45, avatar: null },
  { rank: 4, userId: '13', name: 'Fitri Handayani', points: 3980, trees: 40, avatar: null },
  { rank: 5, userId: '14', name: 'Yusuf Maulana', points: 3750, trees: 38, avatar: null },
  { rank: 6, userId: '15', name: 'Rina Susanti', points: 3420, trees: 35, avatar: null },
  { rank: 7, userId: '16', name: 'Hendra Wijaya', points: 3100, trees: 32, avatar: null },
  { rank: 8, userId: '1', name: 'Ahmad Wijaya', points: 850, trees: 5, avatar: null, isCurrentUser: true },
  { rank: 9, userId: '17', name: 'Mega Putri', points: 780, trees: 8, avatar: null },
  { rank: 10, userId: '18', name: 'Doni Saputra', points: 650, trees: 7, avatar: null },
];

// Mock Community Feed
export const MOCK_COMMUNITY_FEED = [
  {
    id: 'post-1',
    userId: '2',
    userName: 'Budi Santoso',
    userAvatar: null,
    type: 'tree_planted',
    content: 'Baru saja menanam pohon Mahoni di Taman Kota! 🌳',
    treeName: 'Mahoni',
    location: 'Taman Kota Makassar',
    image: null,
    likes: 24,
    comments: 5,
    isLiked: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-2',
    userId: '3',
    userName: 'Sari Dewi',
    userAvatar: null,
    type: 'achievement',
    content: 'Yeay! Dapat badge Tree Guardian! 🏆',
    achievementName: 'Tree Guardian',
    achievementIcon: '🌳',
    image: null,
    likes: 45,
    comments: 12,
    isLiked: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-3',
    userId: '10',
    userName: 'Andi Pratama',
    userAvatar: null,
    type: 'milestone',
    content: 'Sudah 50 pohon tertanam! Target 100 pohon tahun ini 💪',
    image: null,
    likes: 89,
    comments: 23,
    isLiked: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'post-4',
    userId: '11',
    userName: 'Dewi Lestari',
    userAvatar: null,
    type: 'event',
    content: 'Ayo ikut aksi tanam bersama Minggu depan di Pantai Losari! 🌴',
    eventDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    eventLocation: 'Pantai Losari',
    image: null,
    likes: 156,
    comments: 34,
    isLiked: true,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Eco Wallet Transactions
export const MOCK_WALLET_TRANSACTIONS = [
  {
    id: 'txn-1',
    type: 'earn',
    amount: 50,
    description: 'Menanam pohon Mahoni',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    icon: '🌳',
  },
  {
    id: 'txn-2',
    type: 'earn',
    amount: 70,
    description: 'Menyelesaikan streak 7 hari',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    icon: '🔥',
  },
  {
    id: 'txn-3',
    type: 'earn',
    amount: 100,
    description: 'Badge Tree Planter',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    icon: '🏆',
  },
  {
    id: 'txn-4',
    type: 'redeem',
    amount: -200,
    description: 'Tukar voucher diskon',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    icon: '🎁',
  },
  {
    id: 'txn-5',
    type: 'earn',
    amount: 50,
    description: 'Menanam pohon Mangga',
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    icon: '🌳',
  },
];

// Mock Rewards untuk Eco Wallet
export const MOCK_REWARDS = [
  {
    id: 'reward-1',
    name: 'Voucher Kopi 10%',
    description: 'Diskon 10% di kedai kopi partner',
    points: 100,
    image: null,
    icon: '☕',
    partner: 'Kopi Kenangan',
    stock: 50,
  },
  {
    id: 'reward-2',
    name: 'Bibit Pohon Gratis',
    description: '1 bibit pohon pilihan',
    points: 200,
    image: null,
    icon: '🌱',
    partner: 'Dinas Pertamanan',
    stock: 100,
  },
  {
    id: 'reward-3',
    name: 'Voucher Makan 15%',
    description: 'Diskon 15% di resto partner',
    points: 300,
    image: null,
    icon: '🍽️',
    partner: 'Warung Kita',
    stock: 30,
  },
  {
    id: 'reward-4',
    name: 'T-Shirt Aksi Hijau',
    description: 'Kaos eksklusif Aksi Hijau',
    points: 500,
    image: null,
    icon: '👕',
    partner: 'Aksi Hijau',
    stock: 20,
  },
  {
    id: 'reward-5',
    name: 'Tas Ramah Lingkungan',
    description: 'Tas belanja dari bahan daur ulang',
    points: 350,
    image: null,
    icon: '👜',
    partner: 'EcoBag ID',
    stock: 40,
  },
];

// Mock Challenges/Events
export const MOCK_CHALLENGES = [
  {
    id: 'challenge-1',
    title: 'Tantangan Hari Bumi',
    description: 'Tanam 3 pohon untuk memperingati Hari Bumi',
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    requirement: { type: 'trees', count: 3 },
    reward: 150,
    participants: 234,
    progress: 1,
    icon: '🌍',
    isActive: true,
  },
  {
    id: 'challenge-2',
    title: 'Streak Master',
    description: 'Login 14 hari berturut-turut',
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    requirement: { type: 'streak', count: 14 },
    reward: 200,
    participants: 156,
    progress: 7,
    icon: '🔥',
    isActive: true,
  },
  {
    id: 'challenge-3',
    title: 'Photographer Pro',
    description: 'Upload 10 foto dokumentasi pohon',
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirement: { type: 'photos', count: 10 },
    reward: 100,
    participants: 89,
    progress: 3,
    icon: '📸',
    isActive: true,
  },
];

// Mock Learn Content
export const MOCK_LEARN_CONTENT = [
  {
    id: 'learn-1',
    title: 'Cara Menanam Pohon yang Benar',
    description: 'Panduan lengkap menanam pohon agar tumbuh sehat',
    type: 'article',
    duration: '5 menit',
    image: null,
    icon: '📚',
    points: 10,
    isCompleted: true,
  },
  {
    id: 'learn-2',
    title: 'Manfaat Pohon untuk Lingkungan',
    description: 'Pelajari bagaimana pohon membantu bumi',
    type: 'article',
    duration: '7 menit',
    image: null,
    icon: '🌳',
    points: 10,
    isCompleted: true,
  },
  {
    id: 'learn-3',
    title: 'Quiz: Jenis-jenis Pohon',
    description: 'Uji pengetahuanmu tentang jenis pohon',
    type: 'quiz',
    duration: '3 menit',
    image: null,
    icon: '❓',
    points: 25,
    isCompleted: false,
  },
  {
    id: 'learn-4',
    title: 'Video: Teknik Penyiraman',
    description: 'Tutorial menyiram tanaman dengan benar',
    type: 'video',
    duration: '4 menit',
    image: null,
    icon: '🎬',
    points: 15,
    isCompleted: false,
  },
  {
    id: 'learn-5',
    title: 'Perubahan Iklim dan Peran Kita',
    description: 'Memahami dampak perubahan iklim',
    type: 'article',
    duration: '10 menit',
    image: null,
    icon: '🌡️',
    points: 15,
    isCompleted: false,
  },
];

export default {
  MOCK_USERS,
  MOCK_MY_TREES,
  MOCK_COMMUNITY_TREES,
  MOCK_USER_STATS,
  MOCK_UNLOCKED_ACHIEVEMENTS,
  MOCK_ACHIEVEMENT_PROGRESS,
  MOCK_RTH_LOCATIONS,
  MOCK_LEADERBOARD,
  MOCK_COMMUNITY_FEED,
  MOCK_WALLET_TRANSACTIONS,
  MOCK_REWARDS,
  MOCK_CHALLENGES,
  MOCK_LEARN_CONTENT,
};

